@startuml ComponentDiagram
!define RECTANGLE component

' Настройка стиля для ГОСТ
skinparam monochrome true
skinparam shadowing false
skinparam componentFontSize 12
skinparam componentFontName Arial

title Диаграмма компонентов

package "DreamSynth" {
  RECTANGLE "[MidiEditorControl]" as MEC
  RECTANGLE "[EqualizerControl]" as EQC
  RECTANGLE "[Equalizer]" as EQ
  RECTANGLE "[WaveGenerator]" as WG
}

' Зависимости
MEC --> EQC : управляет звуком нот
MEC --> EQ : PlayNote -> ProcessSample
EQC --> EQ : инициализирует и управляет
EQ --> WG : использует для обработки звука

' Легенда
legend right
|= Символ | Описание |
| [ ] | Компонент |
| --> | Зависимость |
endlegend

@enduml