@startuml ComponentDiagram
!define RECTANGLE component

skinparam monochrome true
skinparam shadowing false
skinparam componentFontSize 12
skinparam componentFontName Arial

title Диаграмма компонентов

package "DreamSynth" {
  RECTANGLE "[WaveGenerator]" as WG
  RECTANGLE "[WaveGeneratorControl]" as WGC
  RECTANGLE "[Equalizer]" as EQ
  RECTANGLE "[MidiEditorControl]" as MEC
}

WGC --> WG : управляет
WGC --> EQ : инициализирует
WGC --> MEC : получает ноты
WG --> EQ : использует

@enduml